#!/usr/bin/env python3

import sys
import math

def factorize_rsa(n):
    factors = []
    # Factorize the number
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def main(filename):
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factors_list = factorize_rsa(n)
        factors_str = '*'.join(map(str, factors_list))
        print(f'{n}={factors_str}')

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: rsa <file>')
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
